---
# Turn out all the lights after 00:30
# But only if the TV is off by that point.
#
# https://www.home-assistant.io/docs/automation/examples/
#
alias: 'Lights Out'
trigger:
  platform: time
  at: '00:00:00'
condition:
  condition: state
  entity_id: media_player.livingroom_tv
  state: 'off'
  for:
    minutes: 30
action:
  - service: homeassistant.turn_off
    entity_id: 
      - light.livingroom_lamp
      - light.living_room_light