esphome:
  name: livingroom_tvcabinet_leds
  platform: ESP8266
  board: nodemcuv2

logger:
api:
ota:

wifi:
  ssid: "secret"
  password: "secret"
  fast_connect: true
  
light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: D5
    num_leds: 64
    rgb_order: BRG
    name: "Livingroom TV Cabinet LEDs"
    id: livingroomtvcabinetLEDs
    effects:
      - random:
      - strobe:
    
  - platform: partition
    name: "TV Cabinet LEDs - Left"
    segments:
      # Use first LED from the light with ID light1
      - id: livingroomtvcabinetLEDs
        from: 0
        to: 11
  
  - platform: partition
    name: "TV Cabinet LEDs - Right"
    segments:
      # Use first LED from the light with ID light1
      - id: livingroomtvcabinetLEDs
        from: 12
        to: 63